### ISSUE TITLE
左侧边栏里当前打开文件的背景色建议突出一些

### ISSUE THREAD

**Issue by ArkiZh** [zhaisasi/vscode-themes-zhaisasi#2]
![2022-06-14_18-14](https://user-images.githubusercontent.com/16307158/173554414-041241f5-07c7-4d2a-ba44-c4be0463650c.png)

**Comment by eoioer** [comment]
感谢，稍后就更新一下。
临时解决办法是
在设置文件里输入如下：
    "workbench.colorCustomizations": {
		"list.activeSelectionBackground": "#6b7d8f1f",
		"list.activeSelectionForeground": "#5c6166",
		"list.inactiveSelectionBackground": "#6b7d8f1f",
		"list.inactiveSelectionForeground": "#5c6166",
		"list.focusBackground": "#6b7d8f1f",
		"list.hoverBackground": "#6b7d8f1f",
    },
